[package]
name = "bootstrap"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.32", features = ["derive"] }
p2panda-core = { git = "https://github.com/p2panda/p2panda", rev = "f3a016324b69beac45cf20a792fe6890cb1a21e3" }
p2panda-net = { git = "https://github.com/p2panda/p2panda", rev = "f3a016324b69beac45cf20a792fe6890cb1a21e3" }
p2panda-sync = { git = "https://github.com/p2panda/p2panda", rev = "f3a016324b69beac45cf20a792fe6890cb1a21e3", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.42.0", features = ["rt", "sync"] }
tracing-subscriber = "0.3.19"
