[package]
name = "bootstrap"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
hex = "0.4.3"
p2panda-core = "0.3.1"
p2panda-net = "0.3.1"
p2panda-sync = "0.3.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.0", features = ["rt", "sync"] }
tracing-subscriber = "0.3.19"

[dev-dependencies]
tempfile = "3.19.1"
